### ISSUE TITLE
Language selection?

### ISSUE THREAD

**Issue by zone47** [JeroenDeDauw/QueryrAPI#38]
Hello. After somes tests, this API looks like a great tool which could be so much useful.
What about languages selection ? It seems (maybe I do not understand well) that is not supported for now. Is it  planned ? What will happen if there is no label in requested language ? First an alterntative in English and if there is no, in another language ?

**Comment by jane023** [comment]
Most items are missing labels in some language. For items without any
sitelinks there is generally only one lablel. If you only accept input
through a textlabel then I guess it will still work if you use the Q and P
numbers as those are the defaults, but I am not sure. Having worked a lot
in artworks on Wikidata I have noticed problems looking up artworks with
the same title if the description is blank. There is no disambiguation
because that is what the Q and P numbers are supposed to solve. I think
it's better to keep to a two-step process for those wishing to use text
labels, namely first look up the Q/P numbers and serve both text and
numbers back (if the text is available)

**Comment by zone47** [comment]
Thank you Jane. My question was not clear: it isn't how to query in a specific language but is it possible with a Q to get label for a specific language and what would happen if there is no label in this language.

**Comment by jane023** [comment]
Hmm I would expect if the label doesn't exist that the Q/P number would be returned as default (this is also how it currently works in Autolist when you set the language to a different code and hit download the second time, which is btw the method I used to copy artist name labels from one language to another)

**Comment by JeroenDeDauw** [comment]
These tracking issue for language selection support answers part of your question and asks some of its own: [Add language selection support](https://github.com/JeroenDeDauw/QueryrAPI/issues/12)

Related other issues are:
- [Determine /label and /description behaviour for no such term](https://github.com/JeroenDeDauw/QueryrAPI/issues/14)
- [Determine response format for /label /description and /aliases endpoints](https://github.com/JeroenDeDauw/QueryrAPI/issues/31) (includes the question if language fallback is good to have)

Feel free to reopen or create a new issue if those do not cover all your questions. Feedback on the open questions listed on the linked issues is very welcome.
